services:  
  web:
    build: .
    environment:
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "8080:80"
    volumes:
      - "../src:/var/www/html"
    
      

  
